apiVersion: fluxcd.controlplane.io/v1
kind: FluxInstance
metadata:
    name: flux
    namespace: flux-system
    annotations:
        fluxcd.controlplane.io/reconcileEvery: "1h"
        fluxcd.controlplane.io/reconcileArtifactEvery: "24h"
        fluxcd.controlplane.io/reconcileTimeout: "5m"
spec:
    distribution:
        version: "2.x"
        registry: "ghcr.io/fluxcd"
        artifact: "oci://ghcr.io/controlplaneio-fluxcd/flux-operator-manifests"
    components:
      - source-controller
      - kustomize-controller
    cluster:
        type: kubernetes
        size: small
    sync:
        kind: GitRepository
        url: "https://github.com/v4ldum/vps"
        ref: "refs/heads/main"
        path: "./"
        pullSecret: "ghcr"
