apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- flux-instance.yml
- dozzle.yml
- repositories/backoffice.yml
- repositories/bingo.yml
- repositories/finance.yml
- repositories/heal.yml
- repositories/manganotif.yml
- repositories/portfolio.yml
- repositories/qe.yml
- repositories/shaman.yml
- repositories/thorfinn.yml
