# Keeps the image digest up-to-date
apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSetInputProvider
metadata:
    name: portfolio
    namespace: flux-system
    annotations:
        fluxcd.controlplane.io/reconcileEvery: "5m"
spec:
    type: OCIArtifactTag
    url: oci://ghcr.io/v4ldum/portfolio
    filter:
        includeTag: "^latest$"
        limit: 1
    secretRef:
        name: ghcr

---
apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
    name: portfolio
    namespace: flux-system
spec:
    inputsFrom:
      - kind: ResourceSetInputProvider
        name: portfolio
    resources:
        # Keeps the manifest up-to-date
      - apiVersion: source.toolkit.fluxcd.io/v1
        kind: GitRepository
        metadata:
            name: portfolio
            namespace: flux-system
        spec:
            interval: 5m
            url: https://github.com/V4ldum/portfolio
            ref:
                branch: main
            ignore: |
                /*
                !/kubernetes.yml
            secretRef:
                name: github
        # Keeps the image up-to-date with the digest from RSIP
      - apiVersion: kustomize.toolkit.fluxcd.io/v1
        kind: Kustomization
        metadata:
            name: portfolio
            namespace: flux-system
        spec:
            interval: 5m
            path: ./
            prune: true
            targetNamespace: default
            sourceRef:
                kind: GitRepository
                name: portfolio
            images:
              - name: ghcr.io/v4ldum/portfolio
                digest: << inputs.digest | quote >>
