apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: backoffice
  namespace: flux-system
spec:
    interval: 5m0s
    path: .
    prune: true
    targetNamespace: default
    sourceRef:
        kind: GitRepository
        name: backoffice

---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: backoffice
  namespace: flux-system
spec:
    interval: 5m0s
    url: https://github.com/V4ldum/backoffice
    ref:
        branch: main
    secretRef:
        name: flux-system
    ignore: |
        /*
        !/kubernetes.yml
