apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: finance
  namespace: flux-system
spec:
    interval: 5m0s
    path: .
    prune: true
    targetNamespace: default
    sourceRef:
        kind: GitRepository
        name: finance

---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: finance
  namespace: flux-system
spec:
    interval: 5m0s
    url: https://github.com/V4ldum/finance-back
    ref:
        branch: main
    secretRef:
        name: flux-system
    ignore: |
        /*
        !/kubernetes.yml

---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: finance
  namespace: flux-system
spec:
    interval: 5m0s
    image: ghcr.io/V4ldum/finance
    secretRef:
        name: flux-system
